slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # Frames e Tópicos do robô
    odom_frame: odom
    map_frame: map
    base_frame: traxxas
    scan_topic: /scan
    mode: mapping

    # Configurações do Solver
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: JACOBI
    ceres_trust_region_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Parâmetros de atualização
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000
    enable_interactive_mode: true